BottomNavigation 구현
mash-up-kr/zuzu_Android pull request #3
Opened 2022-07-01 06:16 UTC by 014967

- navigation 라이브러리 추가
- app state holder & scaffold 추가
- Home.kt 에 바텀네비게이션 구현 
- 네비게이션에 쓰일 아이콘 추가
- 네비게이션 배경 컬러 추가

2022-07-01 13:46 UTC, ckddlr0610 requested changes
수고했어요~ZuzuApp에서 Scaffold가 위치해야하는가에 대한 논의가 필요할 것 같은데 의견 부탁드림다

-----

잘못알고 남김...리뷰가 별도의 화면이 아니라 술 상세보기에서 들어가는 화면이라는걸 방금 알았음 하핳

2022-07-01 13:46 UTC, ckddlr0610 commented on app/src/main/java/com/mashup/zuzu/ZuzuApp.kt
> +        }
Scaffold가 Home이 아니라 ZuzuApp에 위치하고 있는데요~지금 코드의 역할로 본다면 ZuzuApp이 모든 화면의 엔트리 포인트가 될 것 같은 느낌인데 이렇게 되면 리뷰 화면에서도 BottomBar가 있을 것 같거든요.
리뷰의 경우 다른 엑티비티로 빼서 개발하면 괜찮긴 한데, ZuzuApp이라는 네이밍 자체가 App 전체에서 사용되는 진입점 같은 역할이라 이것에 대한 논의가 필요할 것 같아요

2022-07-01 13:51 UTC, ckddlr0610 requested changes
이전에 남겨놓은 리뷰는 저의 착오로...ㅎㅎㅎ상관없네요 저 부분에 대해서는

2022-07-01 13:53 UTC, ckddlr0610 approved these changes
Approve

2022-07-03 08:55 UTC, d2fault commented
LGTM!

2022-07-03 08:56 UTC, d2fault approved these changes
리소스 파일은 디자인 완료되면 일괄로 넣어 보아요!
고생했어용 :)

2022-07-03 09:28 UTC, merged